export const GET_COMMISSION_DATA = "GET_COMMISSION_DATA"

export const DELETE_COMMISSION_DATA = "DELETE_COMMISSION_DATA"

export const SAVE_COMMISSION_DATA  = "SAVE_COMMISSION_DATA"

export const UPDATE_COMMISSION_DATA = "UPDATE_COMMISSION_DATA"