export const GET_EMPLOYEE_DATA = "GET_EMPLOYEE_DATA";

export const DELETE_EMPLOYEE_DATA = "DELETE_EMPLOYEE_DATA";

export const EDIT_EMPLOYEE_DATA = "EDIT_EMPLOYEE_DATA";

export const SAVE_EMPLOYEE_DATA = "SAVE_EMPLOYEE_DATA";